"""BEAST2 integration validation tests.

These tests validate that XML generated by Beast2Py passes BEAST2's own
XMLParser validation (headless, no JavaFX required).

Tests are skipped if the beast2_validate.sh script or BEAST2 jars are not found.
"""

import os
import re
import shutil
import subprocess
import tempfile
from pathlib import Path

import pytest

from beast2py.config import ConfigParser
from beast2py.xml_writer import XMLWriter

# Path to the beast2_validate.sh script (repository root)
PROJECT_ROOT = Path(__file__).parent.parent
VALIDATE_SCRIPT = PROJECT_ROOT / "beast2_validate.sh"

# Path to example files
EXAMPLES_DIR = Path(__file__).parent.parent / "examples"


def _find_beast_base_jar():
    """Locate an installed BEAST.base.jar (env override, then ~/.beast/2.7/*)."""
    env_jar = os.environ.get("BEAST2_JAR")
    if env_jar and Path(env_jar).exists():
        return Path(env_jar)
    jars = list(Path.home().glob(".beast/2.7/BEAST.base/*/lib/BEAST.base.jar"))

    def version_key(p):
        # p = .../BEAST.base/<version>/lib/BEAST.base.jar; sort numerically
        m = re.search(r"(\d+(?:\.\d+)*)", p.parents[1].name)
        return tuple(int(x) for x in m.group(1).split(".")) if m else (0,)

    jars.sort(key=version_key)
    return jars[-1] if jars else None


def _validate_with_beast2(xml_path: str) -> tuple:
    """Run BEAST2 validation on an XML file.

    Returns:
        Tuple of (success: bool, output: str).
    """
    result = subprocess.run(
        ["bash", str(VALIDATE_SCRIPT), xml_path],
        capture_output=True,
        text=True,
        timeout=120,
    )
    return result.returncode == 0, result.stdout + result.stderr


def _generate_xml_from_config(config_path: str, output_path: str):
    """Generate XML from a config file.

    Args:
        config_path: Path to the YAML config file.
        output_path: Path to write the XML output.
    """
    parser = ConfigParser()
    config = parser.parse(config_path)
    writer = XMLWriter(config)
    xml_str = writer.generate_xml()
    output_path.write_text(xml_str)


def _find_addon_jar(package_dir_name: str, env_var: str):
    """Locate an installed BEAST2 add-on jar, if any."""
    env_jar = os.environ.get(env_var)
    if env_jar and Path(env_jar).exists():
        return Path(env_jar)
    jars = sorted(Path.home().glob(f".beast/2.7/{package_dir_name}/*/lib/*.jar"))
    return jars[-1] if jars else None


def _java_major_version():
    """Return the major version of the java that beast2_validate.sh will use.

    Returns:
        The major version as an int, or None when java cannot be run.
    """
    java_home = os.environ.get("JAVA_HOME")
    java = Path(java_home) / "bin" / "java" if java_home else Path(shutil.which("java") or "")
    if not java.is_file():
        return None
    try:
        proc = subprocess.run([str(java), "-version"], capture_output=True, text=True, timeout=30)
    except Exception:
        return None
    text = proc.stderr + proc.stdout
    # Lines look like: openjdk version "17.0.9" or "1.8.0_501"
    import re

    match = re.search(r'version "(\d+)(?:\.(\d+))?', text)
    if not match:
        return None
    major = int(match.group(1))
    if major == 1 and match.group(2):  # legacy 1.8 numbering
        major = int(match.group(2))
    return major


# Check if BEAST2 validation is available. Java is part of the check on
# purpose: BEAST 2.7.x refuses to run on anything older than JDK 17, and
# gating only on the presence of the jars turned an unsuitable toolchain into
# a test *failure* instead of an honest skip.
_JAVA_MAJOR = _java_major_version()
BEAST2_AVAILABLE = (
    VALIDATE_SCRIPT.exists()
    and shutil.which("bash") is not None
    and _find_beast_base_jar() is not None
    and _JAVA_MAJOR is not None
    and _JAVA_MAJOR >= 17
)

skip_if_no_beast2 = pytest.mark.skipif(
    not BEAST2_AVAILABLE,
    reason=(
        "BEAST2 integration check unavailable: needs beast2_validate.sh, the "
        "BEAST.base jar and JDK 17+ "
        f"(java detected: {_JAVA_MAJOR if _JAVA_MAJOR is not None else 'none'})"
    ),
)

# Examples whose spec classes live in add-on packages: {config: (pkg dir, env var)}
ADDON_REQUIREMENTS = {
    "config_nested_sampling.yaml": ("NS", "NS_ADDON_JAR"),
    "config_bd_skyline.yaml": ("BDSKY", "BDSKY_ADDON_JAR"),
}


def _config_addon_available(config_name: str) -> bool:
    requirement = ADDON_REQUIREMENTS.get(config_name)
    if requirement is None:
        return True
    return _find_addon_jar(*requirement) is not None


def _list_example_configs():
    return sorted(EXAMPLES_DIR.glob("config_*.yaml"))


@skip_if_no_beast2
class TestBEAST2Validation:
    """Test that generated XML passes BEAST2's own validation.

    Every example configuration in examples/ is generated and validated, so
    new model examples are covered automatically. Configs whose spec classes
    require a BEAST2 add-on are skipped when that add-on is not installed.
    """

    @pytest.mark.parametrize(
        "config_path",
        _list_example_configs(),
        ids=lambda p: p.name,
    )
    def test_config_xml_validates(self, config_path):
        """Test that an example config generates BEAST2-valid XML."""
        if not _config_addon_available(config_path.name):
            pytest.skip(f"add-on package required by {config_path.name} not found")
        with tempfile.NamedTemporaryFile(
            suffix=".xml", mode="w", delete=False, dir=str(EXAMPLES_DIR)
        ) as f:
            xml_path = Path(f.name)
        # The CLI refuses to truncate an existing output without --force, so
        # claim the path and release the file instead of pre-creating it.
        os.unlink(xml_path)
        try:
            _generate_xml_from_config(str(config_path), xml_path)
            success, output = _validate_with_beast2(xml_path)
            assert success, f"BEAST2 validation failed:\n{output}"
            assert "VALID" in output
        finally:
            if os.path.exists(xml_path):
                os.unlink(xml_path)

    def test_example_output_xml_validates(self):
        """Test that the pre-generated example XML passes BEAST2 validation."""
        xml_path = str(EXAMPLES_DIR / "output_basic.xml")
        if not os.path.exists(xml_path):
            pytest.skip(f"Example XML not found: {xml_path}")
        success, output = _validate_with_beast2(xml_path)
        assert success, f"BEAST2 validation failed:\n{output}"
        assert "VALID" in output

    def test_quick_command_xml_validates(self):
        """Test that XML generated via quick command passes BEAST2 validation."""
        from beast2py.main import main

        fasta_path = str(EXAMPLES_DIR / "primates.fasta")
        cal_path = str(EXAMPLES_DIR / "calibrations.yaml")

        with tempfile.NamedTemporaryFile(
            suffix=".xml", mode="w", delete=False, dir=str(EXAMPLES_DIR)
        ) as f:
            xml_path = Path(f.name)
        # The CLI refuses to truncate an existing output without --force, so
        # claim the path and release the file instead of pre-creating it.
        os.unlink(xml_path)

        try:
            ret = main(
                [
                    "quick",
                    "-a",
                    fasta_path,
                    "-o",
                    str(xml_path),
                    "--tree-prior",
                    "yule",
                    "--subst-model",
                    "hky",
                    "--clock-model",
                    "strict",
                    "--calibration-yaml",
                    str(cal_path),
                    "--chain-length",
                    "1000000",
                ]
            )
            assert ret == 0, "quick command failed"

            success, output = _validate_with_beast2(xml_path)
            assert success, f"BEAST2 validation failed:\n{output}"
            assert "VALID" in output
        finally:
            if os.path.exists(xml_path):
                os.unlink(xml_path)
